### PR TITLE
Authenticationbranch

### PR DESCRIPTION
**Pull request by shemalucien**
#### What does this PR do?

- Implements the responsiveness of the sign-in and sign-up pages
-implements the signin and signup authentication

#### Description of Task to be completed? 

-User can be able to signup with firstaname,lastname, email, password and signin using email and password 
-User can be able to see the message in console if he is signed up or signed in
-User can be able to view the page in both desktop ,tablet and mobile view.

#### How should this be manually tested?

- Clone the repo
- checkout to branch 'autenticationbranch'
- pull the changes by running git pull
- Run `npm install` to install modules
- Run `npm  run start` to start the development server

#### What are the relevant Pivotal Tracker/trello stories?

- link to my pivotal tracker/https://trello.com/b/JkUOzgvn/my-portfolio

#### Screenshots 
signin
signup

#### Questions:

- N/A

### CODE REVIEW

**Review by Xldivin — COMMENTED** [review]
remove some small spaces other way nice codes

**Review by PrinceNiyonshuti — APPROVED** [review]
nice work and try to user `alert('New account created')` instead of `console.log`

**Review by Salim-54 — APPROVED** [review]

**Comment by shemalucien** [comment]
thank you prince I'm going to correct it.

**Comment by shemalucien** [comment]
thank you divin

**Pull request merged**
